spring:

  # identity
  application:
    name: Skypeople Web
    
  # profile Setting
  profiles:
    active: local
    
---
# 로컬
spring:
  profiles: local
  
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  
  thymeleaf:
   cache: false
   
  #OAuth2
  security:
    oauth2:
      client:
        registration: 
          google:
            client-id: 976663314267-ql5g51orora4prp9kusge2aet7dclerj.apps.googleusercontent.com
            client-secret: RgrwtJIDtl6OopvU3QueAKZk
            scope: profile,email
          kakao:
            client-id: 6e381405faa01ef62b40f38e81a8a38b
            client-secret: JUFiFCFylnMfpoAbr2kxzw5WQVWsN2l9
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile,account_email
            client-name: Kakao
          naver:
            client-id: Jhbr8k5vF2fpQwmMLuzG
            client-secret: piUP5YrDII
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: nickname,email
            client-name: Naver
            
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
     
server:
  port: 8083
  

---
# 개발
spring:
  profiles: dev
  
---
# 운영  
spring:
  profiles: prod